- name: DNS
  hosts: all
  sudo: true
  vars_files:
  - vars.yml
  roles:
  - { role: recursive, tags: recursive, when: ansible_hostname in groups.recursive }
  - { role: master, tags: master, when: ansible_hostname in groups.master }
  - { role: slave, tags: slave, when: ansible_hostname in groups.slave }
