- set_fact:
    knot_conf: /usr/local/etc/knot/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    knot_conf: /etc/knot/
  when: ansible_system == 'Linux'

- name: Install KnotDNS (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=knot,knot-host,knot-dnsutils state=latest force=yes
  notify: restart knot
- name: Install KnotDNS (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=knot state=latest
  notify: restart knot
- name: Install KnotDNS (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=knot2 state=present
  notify: restart knot
  
- name: Enable KnotDNS (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^knot_enable= line=knot_enable=YES
- name: Enable KnotDNS (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^knot_config=
    line=knot_config=/usr/local/etc/knot/knot.conf

- name: Creates data/ directory
  file: state=directory path={{ knot_conf }}data
  notify: restart knot
- name: Creates kasp/ directory
  file: state=directory path={{ knot_conf }}data/kasp

- name: Clone zones repository
  git: >
    repo=https://github.com/pdostal/server-zones.git
    dest={{ knot_conf }}zones
    force=yes
  notify: reload knot

- name: Paste master config
  template: src=master.conf dest={{ knot_conf }}knot.conf
  notify: restart knot

- name: Set permissions
  file: >
    state=directory
    path={{ knot_conf }}
    recurse=yes
    owner=knot
    group=knot
    mode=0774
  notify: reload knot
