- set_fact:
    unbound_conf: /usr/local/etc/unbound/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    unbound_conf: /etc/unbound/
  when: ansible_system == 'Linux'

- name: Install Unbound (Debian)
  when: ansible_distribution == 'Debian'
  apt: name={{ item }} state=latest
  with_items:
  - unbound
  - unbound-anchor
  - knot-dnsutils
  - knot-host
  notify: restart unbound
- name: Install Unbound (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=unbound state=present
  notify: restart unbound

- name: Enable Unbound (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^unbound_enable= line=unbound_enable=YES
  notify: restart unbound

- name: Paste config
  template: src=unbound.conf dest={{ unbound_conf }}unbound.conf
  notify: restart unbound
